MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # note that backbone weight is not loaded in here
  BACKBONE:
    CONV_BODY: "SPADER-50-FPN"
    DEPTH_PROB: 0.9
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_PER_BATCH: False
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 41 # for NYU 40 classes
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("nyuv2_depth_40_train",)
  TEST: ("nyuv2_depth_40_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (6000, 8000)
  MAX_ITER: 9000
INPUT:
  TO_BGR255: False
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  MIN_SIZE_TRAIN: (480,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 640
OUTPUT_DIR: "expr/nyuv2_spade_maskrcnn"
DTYPE: "float32"